# Generated by Django 4.2.8 on 2023-12-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_messages_options_messages_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='llm_endpoint',
            field=models.URLField(null=True),
        ),
    ]
